global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080'] 

  - job_name: 'ms-pedidos'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ms-pedidos:8081']

  - job_name: 'ms-estoque'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ms-estoque:8082']
  - job_name: 'ms-pagamento'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ms-pagamento:8083']
  - job_name: 'ms-notificacao'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ms-notificacao:8084']